//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LARCA2.Data.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LARCA20_MasterData
    {
        public LARCA20_MasterData()
        {
            this.LARCA20_User_Owner = new HashSet<LARCA20_User_Owner>();
            this.LARCA20_User_Owner1 = new HashSet<LARCA20_User_Owner>();
            this.LARCA20_User_Owner2 = new HashSet<LARCA20_User_Owner>();
            this.LARCA20_SmoScope = new HashSet<LARCA20_SmoScope>();
            this.LARCA20_SmoScopeDetail = new HashSet<LARCA20_SmoScopeDetail>();
            this.LARCA20_SmoScope1 = new HashSet<LARCA20_SmoScope>();
            this.LARCA20_SmoScopeDetail1 = new HashSet<LARCA20_SmoScopeDetail>();
            this.LARCA20_SmoScopeDetail2 = new HashSet<LARCA20_SmoScopeDetail>();
            this.LARCA20_SmoScope2 = new HashSet<LARCA20_SmoScope>();
            this.LARCA20_SmoScopeDetail3 = new HashSet<LARCA20_SmoScopeDetail>();
        }
    
        public long IdRenglon { get; set; }
        public string Data { get; set; }
        public string DataIni { get; set; }
        public string DataFin { get; set; }
        public bool Borrado { get; set; }
    
        public virtual ICollection<LARCA20_User_Owner> LARCA20_User_Owner { get; set; }
        public virtual ICollection<LARCA20_User_Owner> LARCA20_User_Owner1 { get; set; }
        public virtual ICollection<LARCA20_User_Owner> LARCA20_User_Owner2 { get; set; }
        public virtual ICollection<LARCA20_SmoScope> LARCA20_SmoScope { get; set; }
        public virtual ICollection<LARCA20_SmoScopeDetail> LARCA20_SmoScopeDetail { get; set; }
        public virtual ICollection<LARCA20_SmoScope> LARCA20_SmoScope1 { get; set; }
        public virtual ICollection<LARCA20_SmoScopeDetail> LARCA20_SmoScopeDetail1 { get; set; }
        public virtual ICollection<LARCA20_SmoScopeDetail> LARCA20_SmoScopeDetail2 { get; set; }
        public virtual ICollection<LARCA20_SmoScope> LARCA20_SmoScope2 { get; set; }
        public virtual ICollection<LARCA20_SmoScopeDetail> LARCA20_SmoScopeDetail3 { get; set; }
    }
}
