//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LARCA2.Data.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LARCA20_UsuariosRoles
    {
        public int IdRenglon { get; set; }
        public int RefIdUsuario { get; set; }
        public int RefIdRoles { get; set; }
        public bool Borrado { get; set; }
    
        public virtual LARCA20_Roles LARCA20_Roles { get; set; }
        public virtual LARCA20_Usuarios LARCA20_Usuarios { get; set; }
    }
}
