//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LARCA2.Data.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LARCA20_Users
    {
        public LARCA20_Users()
        {
            this.LARCA20_User_Owner = new HashSet<LARCA20_User_Owner>();
            this.LARCA20_UsersRoles = new HashSet<LARCA20_UsersRoles>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string last_name { get; set; }
        public string Email { get; set; }
        public string telephone { get; set; }
        public string user_name { get; set; }
        public string pass { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public bool deleted { get; set; }
    
        public virtual ICollection<LARCA20_User_Owner> LARCA20_User_Owner { get; set; }
        public virtual ICollection<LARCA20_UsersRoles> LARCA20_UsersRoles { get; set; }
    }
}
