//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LARCA2.Data.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LARCA20_User_Owner
    {
        public long Id { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<long> IdOwner { get; set; }
        public Nullable<long> IdSmo { get; set; }
        public Nullable<long> IdBU { get; set; }
        public Nullable<bool> deleted { get; set; }
    
        public virtual LARCA20_MasterData LARCA20_MasterData { get; set; }
        public virtual LARCA20_MasterData LARCA20_MasterData1 { get; set; }
        public virtual LARCA20_MasterData LARCA20_MasterData2 { get; set; }
        public virtual LARCA20_User_Owner LARCA20_User_Owner1 { get; set; }
        public virtual LARCA20_User_Owner LARCA20_User_Owner2 { get; set; }
        public virtual LARCA20_User_Owner LARCA20_User_Owner11 { get; set; }
        public virtual LARCA20_User_Owner LARCA20_User_Owner3 { get; set; }
        public virtual LARCA20_Users LARCA20_Users { get; set; }
    }
}
