//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LARCA2.Data.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LARCA20_SmoScopeDetail
    {
        public long DetailID { get; set; }
        public Nullable<long> SmoScopeID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<long> SmoID { get; set; }
        public Nullable<long> BuID { get; set; }
        public Nullable<long> OwnerID { get; set; }
        public Nullable<long> Lvl2ID { get; set; }
        public Nullable<long> Lvl3ID { get; set; }
        public decimal Volumen { get; set; }
        public Nullable<long> ReasonID { get; set; }
        public string Customer { get; set; }
        public bool deleted { get; set; }
        public string originaldate { get; set; }
    
        public virtual LARCA20_MasterData MasterBUDetail { get; set; }
        public virtual LARCA20_MasterData MasterOwnerDetail { get; set; }
        public virtual LARCA20_MasterData MasterReasonDetail { get; set; }
        public virtual LARCA20_MasterData MasterSMODetail { get; set; }
        public virtual LARCA20_RcClasification MasterLvl2Detail { get; set; }
        public virtual LARCA20_RcClasification MasterLvl3Detail { get; set; }
        public virtual LARCA20_SmoScope SmoScopeDetail { get; set; }
    }
}
