//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LARCA2.Data.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LARCA20_Emails
    {
        public long EmailID { get; set; }
        public int TipoProceso { get; set; }
        public string MessageID { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Archivo { get; set; }
        public bool Procesado { get; set; }
        public bool Borrado { get; set; }
    }
}
