//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LARCA2.Data.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LARCA20_Roles
    {
        public LARCA20_Roles()
        {
            this.LARCA20_RolesRecursos = new HashSet<LARCA20_RolesRecursos>();
            this.LARCA20_UsuariosRoles = new HashSet<LARCA20_UsuariosRoles>();
        }
    
        public int IdRenglon { get; set; }
        public string Descripcion { get; set; }
        public bool Borrado { get; set; }
    
        public virtual ICollection<LARCA20_RolesRecursos> LARCA20_RolesRecursos { get; set; }
        public virtual ICollection<LARCA20_UsuariosRoles> LARCA20_UsuariosRoles { get; set; }
    }
}
