//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LARCA2.Data.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LARCA20_RcClasification
    {
        public LARCA20_RcClasification()
        {
            this.LARCA20_Level4 = new HashSet<LARCA20_Level4>();
            this.LARCA20_SmoScope = new HashSet<LARCA20_SmoScope>();
            this.LARCA20_SmoScopeDetail = new HashSet<LARCA20_SmoScopeDetail>();
            this.LARCA20_SmoScopeDetail1 = new HashSet<LARCA20_SmoScopeDetail>();
        }
    
        public long IdRenglon { get; set; }
        public string Nivel { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string Ownership { get; set; }
        public bool Borrado { get; set; }
    
        public virtual ICollection<LARCA20_Level4> LARCA20_Level4 { get; set; }
        public virtual ICollection<LARCA20_SmoScope> LARCA20_SmoScope { get; set; }
        public virtual ICollection<LARCA20_SmoScopeDetail> LARCA20_SmoScopeDetail { get; set; }
        public virtual ICollection<LARCA20_SmoScopeDetail> LARCA20_SmoScopeDetail1 { get; set; }
    }
}
