//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LARCA2.Data.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LARCA20_Emails
    {
        public long EmailID { get; set; }
        public string MessageID { get; set; }
        public int processtype { get; set; }
        public System.DateTime date { get; set; }
        public string filename { get; set; }
        public bool processed { get; set; }
        public bool deleted { get; set; }
    }
}
