//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LARCA2.Data.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LARCA20_ImputOriginal
    {
        public int IdRenglon { get; set; }
        public string Day { get; set; }
        public string FPC { get; set; }
        public string RepCountry { get; set; }
        public string ProfitCenter { get; set; }
        public string ReasonCode { get; set; }
        public string CFR { get; set; }
        public string SapSite { get; set; }
        public string Customer { get; set; }
        public Nullable<decimal> SU_Cases { get; set; }
        public bool Borrado { get; set; }
    }
}
