//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LARCA2.Data.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LARCA20_SmoScopeGroup
    {
        public int IdRenglon { get; set; }
        public Nullable<int> RefIdFrom { get; set; }
        public Nullable<int> RefIdTo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public bool Borrado { get; set; }
    }
}
