//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LARCA2.Data.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LARCA20_Responsable
    {
        public LARCA20_Responsable()
        {
            this.LARCA20_SmoScope = new HashSet<LARCA20_SmoScope>();
        }
    
        public int IdRenglon { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Email { get; set; }
        public Nullable<int> RefIdUsuario { get; set; }
        public bool Borrado { get; set; }
    
        public virtual ICollection<LARCA20_SmoScope> LARCA20_SmoScope { get; set; }
    }
}
