//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LARCA2.Data.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LARCA20_Usuarios
    {
        public LARCA20_Usuarios()
        {
            this.LARCA20_User_Owner = new HashSet<LARCA20_User_Owner>();
            this.LARCA20_UsuariosRoles = new HashSet<LARCA20_UsuariosRoles>();
        }
    
        public int IdRenglon { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string Usuario { get; set; }
        public string Clave { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public bool Borrado { get; set; }
    
        public virtual ICollection<LARCA20_User_Owner> LARCA20_User_Owner { get; set; }
        public virtual ICollection<LARCA20_UsuariosRoles> LARCA20_UsuariosRoles { get; set; }
    }
}
