//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LARCA2.Data.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LARCA20_AuxData
    {
        public long RowId { get; set; }
        public int TopLvl2 { get; set; }
        public int TopLvl3 { get; set; }
        public int XlsRowFrom { get; set; }
        public int XlsColumnFrom { get; set; }
        public int Toplvl4 { get; set; }
        public int CntAdjuntos { get; set; }
        public int LimiteFiltro { get; set; }
        public int DiasReporte { get; set; }
        public Nullable<int> SmoDays { get; set; }
    }
}
