//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LARCA2.Data.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LARCA20_RcClasification
    {
        public LARCA20_RcClasification()
        {
            this.LARCA20_SmoScopeDetail = new HashSet<LARCA20_SmoScopeDetail>();
            this.LARCA20_SmoScopeDetail1 = new HashSet<LARCA20_SmoScopeDetail>();
            this.LARCA20_SmoScope = new HashSet<LARCA20_SmoScope>();
        }
    
        public long Id { get; set; }
        public string level_name { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string Ownership { get; set; }
        public bool deleted { get; set; }
    
        public virtual ICollection<LARCA20_SmoScopeDetail> LARCA20_SmoScopeDetail { get; set; }
        public virtual ICollection<LARCA20_SmoScopeDetail> LARCA20_SmoScopeDetail1 { get; set; }
        public virtual ICollection<LARCA20_SmoScope> LARCA20_SmoScope { get; set; }
    }
}
