//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LARCA2.Data.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LARCA20_Level4
    {
        public long Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<long> RefIdLevel3 { get; set; }
        public Nullable<bool> Borrado { get; set; }
    
        public virtual LARCA20_RcClasification LARCA20_RcClasification { get; set; }
    }
}
