//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LARCA2.Data.DatabaseModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Larca2Entities : DbContext
    {
        public Larca2Entities()
            : base("name=Larca2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LARCA20_AuxData> LARCA20_AuxData { get; set; }
        public virtual DbSet<LARCA20_Emails> LARCA20_Emails { get; set; }
        public virtual DbSet<LARCA20_ImputOriginal> LARCA20_ImputOriginal { get; set; }
        public virtual DbSet<LARCA20_Mailing> LARCA20_Mailing { get; set; }
        public virtual DbSet<LARCA20_MasterDataSMOLess> LARCA20_MasterDataSMOLess { get; set; }
        public virtual DbSet<LARCA20_Responsable> LARCA20_Responsable { get; set; }
        public virtual DbSet<LARCA20_Roles> LARCA20_Roles { get; set; }
        public virtual DbSet<LARCA20_SmoScope> LARCA20_SmoScope { get; set; }
        public virtual DbSet<LARCA20_SmoScopeDetail> LARCA20_SmoScopeDetail { get; set; }
        public virtual DbSet<LARCA20_SmoScopeGroup> LARCA20_SmoScopeGroup { get; set; }
        public virtual DbSet<LARCA20_User_Owner> LARCA20_User_Owner { get; set; }
        public virtual DbSet<LARCA20_Users> LARCA20_Users { get; set; }
        public virtual DbSet<LARCA20_UsersRoles> LARCA20_UsersRoles { get; set; }
        public virtual DbSet<LARCA20_Level4> LARCA20_Level4 { get; set; }
        public virtual DbSet<LARCA20_MasterData> LARCA20_MasterData { get; set; }
        public virtual DbSet<LARCA20_RcClasification> LARCA20_RcClasification { get; set; }
        public virtual DbSet<LARCA20_SmoScopeGroupedRows> LARCA20_SmoScopeGroupedRows { get; set; }
    
        public virtual ObjectResult<Nullable<decimal>> SP_VOLUMEN(Nullable<int> tipo, Nullable<long> smo, Nullable<long> bu, string level)
        {
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(int));
    
            var smoParameter = smo.HasValue ?
                new ObjectParameter("smo", smo) :
                new ObjectParameter("smo", typeof(long));
    
            var buParameter = bu.HasValue ?
                new ObjectParameter("bu", bu) :
                new ObjectParameter("bu", typeof(long));
    
            var levelParameter = level != null ?
                new ObjectParameter("level", level) :
                new ObjectParameter("level", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("SP_VOLUMEN", tipoParameter, smoParameter, buParameter, levelParameter);
        }
    }
}
