//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LARCA2.Data.DatabaseModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Larca2Entities : DbContext
    {
        public Larca2Entities()
            : base("name=Larca2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LARCA20_AuxData> LARCA20_AuxData { get; set; }
        public virtual DbSet<LARCA20_Emails> LARCA20_Emails { get; set; }
        public virtual DbSet<LARCA20_ImputOriginal> LARCA20_ImputOriginal { get; set; }
        public virtual DbSet<LARCA20_Level4> LARCA20_Level4 { get; set; }
        public virtual DbSet<LARCA20_Mailing> LARCA20_Mailing { get; set; }
        public virtual DbSet<LARCA20_MasterData> LARCA20_MasterData { get; set; }
        public virtual DbSet<LARCA20_MasterDataSMOLess> LARCA20_MasterDataSMOLess { get; set; }
        public virtual DbSet<LARCA20_RcClasification> LARCA20_RcClasification { get; set; }
        public virtual DbSet<LARCA20_Recursos> LARCA20_Recursos { get; set; }
        public virtual DbSet<LARCA20_Responsable> LARCA20_Responsable { get; set; }
        public virtual DbSet<LARCA20_Roles> LARCA20_Roles { get; set; }
        public virtual DbSet<LARCA20_RolesRecursos> LARCA20_RolesRecursos { get; set; }
        public virtual DbSet<LARCA20_SmoScope> LARCA20_SmoScope { get; set; }
        public virtual DbSet<LARCA20_SmoScopeDetail> LARCA20_SmoScopeDetail { get; set; }
        public virtual DbSet<LARCA20_SmoScopeGroup> LARCA20_SmoScopeGroup { get; set; }
        public virtual DbSet<LARCA20_User_Owner> LARCA20_User_Owner { get; set; }
        public virtual DbSet<LARCA20_Usuarios> LARCA20_Usuarios { get; set; }
        public virtual DbSet<LARCA20_UsuariosRoles> LARCA20_UsuariosRoles { get; set; }
    }
}
